import os

DB_PATH = os.getenv("ACTIVITY_DB_PATH", "activity_monitor.db")
API_KEY = os.getenv("SERVER_API_KEY", "secret")
GET_RATE_LIMIT_WINDOW_SEC = os.getenv("GET_RATE_LIMIT_WINDOW_SEC", "60")
GET_RATE_LIMIT_MAX_REQUESTS = os.getenv("GET_RATE_LIMIT_MAX_REQUESTS", "30")
GET_RATE_LIMIT = f"{GET_RATE_LIMIT_MAX_REQUESTS} per {GET_RATE_LIMIT_WINDOW_SEC} second"

FOURTEEN_DAYS_MS = 14 * 24 * 60 * 60 * 1000
FIVE_MIN_MS = 5 * 60 * 1000
